dist: trusty
branches:
  except:
  - "/^v[0-9]/"
language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
sudo: false
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
install:
- sh -x travis-shell-scripts/install-spark.sh
sbt_args:
- "-Xmx1536M"
- "-XX:+UseConcMarkSweepGC"
- "-XX:+CMSClassUnloadingEnabled"
- "-Xss2M"
script:
- sbt clean coverage test coverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - ecurtin@us.ibm.com
before_deploy:
- sh travis-shell-scripts/set_tags.sh
- sbt dist
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gkFq/Heisi7AJmJ4kdQALAjun7hjdIyjUkTcyqBzBEooL4k/j+1lW3CBDdOgSW4Kn4Juq2/jVuV0iyK/G3Btwinh2H3Fgc+bKJ/QxCCV6OhDXm4aYI9FFOw696glgPZPhFccSwBHZFiKmJ7rXThL8apdLMvhRYIOR+idj3Y/PoVOxXMt8eb+L8NGENtbEqPL+7dtKQuoQsGPTjyu29Bg1XPw5UXB/Dvsbuxl5Sf3XKivo9qoEbUTAbrg3lP7YKgyGaDJ17iM5J8R25zzYgxS1MZZ5eGuQ4qty3aMzhTLV8dKPGWeNI/6fQUKxF1VnKBb9LinksEUbOhidzdQA/FActWakV/h/amBcGYYy0vXKhtrPd/y672wWae0OUyAPtlzOFxLBRb5OwAlBy5b7hD3bsIgfmAdU6ONF73H2Hu04/NGVY5OEfNFzl0RlIyN0f+oDVZmA97ODR/MMi1Hd/VyuqRw7u6Z0YYEOwE8HFETWHgRTDcbv8Xl3vDRz9fLcYb3Nj312np/oazk9VucgezozSScpPZS5hCB/7Qp3900UnTZghOcqnkWr98QqTbEl7FYMSDT/bGS8RDsI/3mWnOl3heCDucFOIfPPDs3h24SXltnKSukiR3wvyPelh4gadJvkSBYfhxdFanv2IeqN4RHttmR1GdqPebqJMOCUWCpYIQ=
  file_glob: true
  file: spark-bench_*.tgz
  on:
    tags: false
    repo: SparkTC/spark-bench
    branch:
    - master
env:
  global:
  - SPARK_HOME=/home/travis/spark-2.1.1-bin-hadoop2.7
