language: scala
scala:
   - 2.11.8
jdk:
  - oraclejdk8
sudo: false
script:
  - sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - ecurtin@us.ibm.com