# The parameters for data generation. 100 million points roughly produces 36GB data size
NUM_OF_POINTS=1000
NUM_OF_CLUSTERS=2
DIMENSIONS=20
SCALING=0.6
NUM_OF_PARTITIONS=2

MAX_ITERATION=2
NUM_RUN=1

SPARK_STORAGE_MEMORYFRACTION=0.48
